// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    } 
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCXc5lclocm3RLaJwGBc88x-Lj07IJ6So',
    appId: '1:643979588576:web:b6db9b9cf4a58e87317185',
    messagingSenderId: '643979588576',
    projectId: 'laporin-89b57',
    authDomain: 'laporin-89b57.firebaseapp.com',
    databaseURL: 'https://laporin-89b57-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laporin-89b57.appspot.com',
    measurementId: 'G-8FTFERTNRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZe1OoPYWOUqZqUi9i2EVhpxb2XU5EWN0',
    appId: '1:643979588576:android:f70571a33888747e317185',
    messagingSenderId: '643979588576',
    projectId: 'laporin-89b57',
    databaseURL: 'https://laporin-89b57-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laporin-89b57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-4fmS3sXjZQWWp74NsJTXR7QpqWvkKu4',
    appId: '1:643979588576:ios:ce2b13052d299d9e317185',
    messagingSenderId: '643979588576',
    projectId: 'laporin-89b57',
    databaseURL: 'https://laporin-89b57-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laporin-89b57.appspot.com',
    androidClientId: '643979588576-4bmmr2ejg0pjm0p5ckgofmt7eu6mgnj8.apps.googleusercontent.com',
    iosClientId: '643979588576-m8c43fhaehur58m2go7ao706nbcdi4oq.apps.googleusercontent.com',
    iosBundleId: 'com.example.laporIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-4fmS3sXjZQWWp74NsJTXR7QpqWvkKu4',
    appId: '1:643979588576:ios:ce2b13052d299d9e317185',
    messagingSenderId: '643979588576',
    projectId: 'laporin-89b57',
    databaseURL: 'https://laporin-89b57-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'laporin-89b57.appspot.com',
    androidClientId: '643979588576-4bmmr2ejg0pjm0p5ckgofmt7eu6mgnj8.apps.googleusercontent.com',
    iosClientId: '643979588576-m8c43fhaehur58m2go7ao706nbcdi4oq.apps.googleusercontent.com',
    iosBundleId: 'com.example.laporIn',
  );
}
